In [1]:
import pandas as pd
import arcgis
pd.set_option("display.max_columns", None)

# From LIR/addr pt

In [3]:
waco_parcels = pd.DataFrame.spatial.from_featureclass(r"C:\gis\Projects\HousingInventory\WashingtonCo.gdb\washington_lir_20231208")
waco_parcels.head()

,OBJECTID,county_name,county_id,assessor_src,boundary_src,disclaimer,current_asof,parcel_id,serial_num,parcel_add,parcel_city,taxexempt_type,tax_district,total_mkt_value,land_mkt_value,parcel_acres,prop_class,primary_res,house_cnt,subdiv_name,bldg_sqft,bldg_sqft_info,floors_cnt,floors_info,built_yr,effbuilt_yr,const_material,SHAPE
0,1,Washington County,27,https://www.washco.utah.gov/departments/assessor/,https://www.washco.utah.gov/departments/recorder/,http://www.utah.gov/disclaimer.html,2023-09-20,SG-SJP-13,0386881,1202 E ST JAMES LN,St. George,None,08,583200.0,125000.0,0.23,Residential,Y,None,ST JAMES PLACE,3007.0,None,1.0,None,1990.0,None,Frame Stucco,"{""rings"": [[[272614.1719000004, 4106772.744699..."
1,2,Washington County,27,https://www.washco.utah.gov/departments/assessor/,https://www.washco.utah.gov/departments/recorder/,http://www.utah.gov/disclaimer.html,2023-09-20,SG-RCCC-14-A,0054166,878 W 1300 N,St. George,None,08,472500.0,95000.0,0.31,Residential,N,None,RED CLIFF COUNTRY CLUB EST,2049.0,None,1.0,None,1990.0,None,Frame Stucco,"{""rings"": [[[268899.9769000001, 4112538.534299..."
2,3,Washington County,27,https://www.washco.utah.gov/departments/assessor/,https://www.washco.utah.gov/departments/recorder/,http://www.utah.gov/disclaimer.html,2023-09-20,I-SCW-1-1,0850484,320 W 25 S,Ivins,None,04,366400.0,110000.0,0.18,Residential,N,None,SUN CREST WEST SUB PH 1,1128.0,None,1.0,None,2008.0,None,Frame Syn Plaster,"{""rings"": [[[261452.8298000004, 4116898.0405],..."
3,4,Washington County,27,https://www.washco.utah.gov/departments/assessor/,https://www.washco.utah.gov/departments/recorder/,http://www.utah.gov/disclaimer.html,2023-09-20,SG-DHT-7,1020019,3239 S 840 E UNIT 7,St. George,None,08,350500.0,85000.0,0.02,Residential,N,None,DESERT HILLS TOWNHOMES,1437.0,None,2.0,None,2019.0,None,Frame Syn Plaster,"{""rings"": [[[271785.70770000014, 4103823.85480..."
4,5,Washington County,27,https://www.washco.utah.gov/departments/assessor/,https://www.washco.utah.gov/departments/recorder/,http://www.utah.gov/disclaimer.html,2023-09-20,SG-GSR-1-110,0939790,1132 W JUST FOR FUN WAY,St. George,None,08,279600.0,60000.0,0.03,Commercial,N,None,GARAGES AT SUN RIVER STORAGE PH 1,1250.0,None,NaN,None,2015.0,None,None,"{""rings"": [[[268115.2297, 4101794.558599999], ..."

In [4]:
waco_parcels['prop_class'].value_counts()

Residential                       78737
Vacant                            21455
Commercial                         6210
Commercial - Apartment & Condo     3097
Unknown                            1386
Name: prop_class, dtype: int64

In [5]:
waco_parcels['primary_res'].value_counts()

N    63134
Y    47751
Name: primary_res, dtype: int64

In [6]:
waco_parcels['house_cnt'].value_counts()

Series([], Name: house_cnt, dtype: int64)

In [7]:
waco_parcels['taxexempt_type'].value_counts()

Series([], Name: taxexempt_type, dtype: int64)

In [8]:
waco_parcels['floors_info'].value_counts()

Series([], Name: floors_info, dtype: int64)

In [9]:
waco_parcels['tax_district'].value_counts()

08    50070
13    15490
03    12722
04     5789
09     3895
47     3208
05     2174
15     1762
41     1558
35     1340
01     1291
11     1231
38     1089
10     1009
45      964
02      695
12      692
06      687
49      613
48      566
53      548
22      504
18      462
27      458
34      430
65      351
28      287
07      235
52      148
29      137
51      133
32       40
64       38
40       37
46       29
71       28
73       28
69       26
44       25
50       18
72       16
55       13
68       12
54       11
70        8
63        5
66        3
62        3
61        2
58        1
60        1
59        1
56        1
57        1
Name: tax_district, dtype: int64

In [19]:
waco_addr_pts = pd.DataFrame.spatial.from_featureclass(r"C:\gis\Projects\HousingInventory\WashingtonCo.gdb\address_points_20231208")
waco_addr_pts.head()

,OBJECTID,addsystem,utaddptid,fulladd,addnum,addnumsuffix,prefixdir,streetname,streettype,suffixdir,...,countyid,state,ptlocation,pttype,structure,parcelid,addsource,loaddate,usng,SHAPE
0,230623,ST GEORGE,ST GEORGE | 7124 N SPRING HOLLOW LOOP,7124 N SPRING HOLLOW LOOP,7124,,N,SPRING HOLLOW,LOOP,,...,49053,UT,,,,,DABC,2023-10-11,12STG7324,"{""x"": 273868.98000000045, ""y"": 4124037.7200000..."
1,1263206,ST GEORGE,ST GEORGE | 1343 W 410 N,1343 W 410 N,1343,,W,410,,N,...,49053,UT,Unknown,Residential,Unknown,SG-GS-9-5,WASHINGTON COUNTY,2023-11-14,12STG6710,"{""x"": 267911.4199999999, ""y"": 4110842.17999999..."
2,1263207,ST GEORGE,ST GEORGE | 1775 W 1300 N,1775 W 1300 N,1775,,W,1300,,N,...,49053,UT,Unknown,Residential,Unknown,SG-JCR-33,WASHINGTON COUNTY,2023-11-14,12STG6712,"{""x"": 267107.26999999955, ""y"": 4112586.5399999..."
3,1263208,CENTRAL,CENTRAL | 412 E BAKER DAM RD N,412 E BAKER DAM RD N,412,,E,BAKER DAM,RD,N,...,49053,UT,Unknown,Unknown,Unknown,C-51-NW,WASHINGTON COUNTY,2023-11-14,12STG6742,"{""x"": 267886.20999999996, ""y"": 4142686.8900000..."
4,1263209,WASHINGTON,WASHINGTON | 720 N MONTEVERDE CIR,720 N MONTEVERDE CIR,720,,N,MONTEVERDE,CIR,,...,49053,UT,Unknown,Residential,Unknown,W-MOGS-3-32,WASHINGTON COUNTY,2023-11-14,12STG7513,"{""x"": 275936.5, ""y"": 4113525.039999999, ""spati..."

In [20]:
waco_addr_pts['building'].value_counts()

    98303
Name: building, dtype: Int64

In [21]:
waco_addr_pts['unittype'].value_counts()

        72438
UNIT    20314
APT      3537
STE       751
SPC       497
LOT       451
TRLR      268
HNGR       42
BSMT        3
FL          1
OFC         1
Name: unittype, dtype: Int64

In [22]:
waco_addr_pts['unitid'].value_counts()

         72428
2          731
1          727
3          572
4          546
         ...
A328         1
539          1
1000B        1
104 D        1
G18          1
Name: unitid, Length: 2874, dtype: Int64

In [23]:
waco_addr_pts['pttype'].value_counts()

Residential     80815
Other            7874
Commercial       6078
Unknown          2657
BASE ADDRESS      878
                    1
Name: pttype, dtype: Int64

# From WashCo

In [2]:
wascho_cama_df = pd.read_csv("C:\gis\Projects\HousingInventory\Data\Washington\WashCo_cama.csv", thousands=",")
wascho_cama_df.head()

C:\Users\jdadams\AppData\Local\Temp\1\ipykernel_12596\220524273.py:1: DtypeWarning: Columns (16,21) have mixed types. Specify dtype option on import or set low_memory=False.
  wascho_cama_df = pd.read_csv("C:\gis\Projects\HousingInventory\Data\Washington\WashCo_cama.csv", thousands=",")

,ACCOUNTNO,PARCELNO,ACCTTYPE,TAXAREA,IMPNO,TOTALUNITCOUNT,IMPSF,PROPERTYTYPE,TOTALVALUE,ACRES,LANDVALUE,IMPEXTERIOR,BLTASSTORIES,BLTASYEARBUILT,BLTASDESCRIPTION,PRIMARY_NONPRIMARY,STREETNO,PREDIRECTION,STREETNAME,PROPERTYCITY,STREETTYPE,PROPERTYZIPCODE,SITUS,SUBDIVISIONNAME
0,11,SG-1-A,Residential,8,1.0,1.0,2268.0,Residential,482400,0.21,97800,Frame Stucco,1.0,1940.0,1 1/2 Story Fin,RES IMPROVEMENT-PRIMARY,175,E,300 S,ST GEORGE,ST,84770.0,175 E 300 S ST ST GEORGE 84770,ST GEORGE CITY SUR PLAT A BLK 1
1,37,SG-1-C,Residential,8,1.0,1.0,1496.0,Residential,385200,0.23,97800,Frame Masonry Veneer,1.0,1975.0,Ranch 1 Story,RES IMPROVEMENT-PRIMARY,185,E,300 S,ST GEORGE,ST,847700000.0,185 E 300 S ST ST GEORGE 847700000,ST GEORGE CITY SURVEY
2,45,SG-2,Residential,8,1.0,1.0,1363.0,Residential,294600,0.09,72300,Frame Stucco,1.0,1924.0,Ranch 1 Story,RES IMPROVEMENT-PRIMARY,286,S,200 E,ST GEORGE,ST,847700000.0,286 S 200 E ST ST GEORGE 847700000,ST GEORGE CITY SURVEY
3,52,SG-3-A,Residential,8,1.0,1.0,2489.0,Residential,679500,0.27,97800,Frame Stucco,1.0,2006.0,Ranch 1 Story,RES IMPROVEMENT-PRIMARY,167,E,300 S,ST GEORGE,ST,847700000.0,167 E 300 S ST ST GEORGE 847700000,ST GEORGE CITY SURVEY
4,60,SG-4,Residential,8,1.0,1.0,832.0,Residential,266200,0.10,76500,Frame Stucco,1.0,1910.0,Ranch 1 Story,RESIDENTIAL - NON-PRIMARY,105,E,300 S,ST GEORGE,ST,847700000.0,105 E 300 S ST ST GEORGE 847700000,ST GEORGE CITY SURVEY

In [3]:
wascho_cama_df['PRIMARY_NONPRIMARY'].value_counts()

PRIMARY_NONPRIMARY
RES IMPROVEMENT-PRIMARY               40894
PLANNED UNIT DEV - PRIMARY            13689
RESIDENTIAL - NON-PRIMARY              9371
PLANNED UNIT DEV - NON-PRIMARY         7352
MOBILE HOMES - PRIMARY                 2285
SERVICE                                2230
OTHER RES-INC MULTI FAMILY-PRIM        1603
MANUFACTURING/INDUSTRIAL               1562
MOBILE HOME - NON-PRIMARY              1104
EXEMPT IMPROVEMENT                     1065
RETAIL SALES                            919
AGRICULTURAL BUILDINGS                  596
OTHER COMMERCIAL IMPROVEMENT            528
RECREATIONAL                             95
OTHER AG BUILDING                        79
OTHER RES-INC MULTI FAMILY-NON-PRI       72
MIXED USE COMMERCIAL                     62
MEDICAL                                  42
MIXED USE RES IMP - PRIMARY              41
MIXED USE RES - NON-PRIMARY              23
AG IMPROVEMENT NOT BUILDINGS              9
Name: count, dtype: int64

In [4]:
wascho_cama_df[wascho_cama_df["PARCELNO"] == "W-164-A-N"]

,ACCOUNTNO,PARCELNO,ACCTTYPE,TAXAREA,IMPNO,TOTALUNITCOUNT,IMPSF,PROPERTYTYPE,TOTALVALUE,ACRES,LANDVALUE,IMPEXTERIOR,BLTASSTORIES,BLTASYEARBUILT,BLTASDESCRIPTION,PRIMARY_NONPRIMARY,STREETNO,PREDIRECTION,STREETNAME,PROPERTYCITY,STREETTYPE,PROPERTYZIPCODE,SITUS,SUBDIVISIONNAME
9942,118623,W-164-A-N,Commercial,13,1.0,0.0,1.0,Commercial,259700,0.9,235200,NaN,1.0,1970.0,Mobile Home/RV Parks *CODE,MOBILE HOMES - PRIMARY,501,N,200 E,WASHINGTON,NaN,847800000.0,NaN,WASHINGTON TOWN RESRVY

In [5]:
wascho_cama_df["PARCELNO"].duplicated(keep=False).value_counts()

PARCELNO
False    94702
True      7908
Name: count, dtype: int64

In [6]:
wascho_cama_df[wascho_cama_df["PARCELNO"].duplicated(keep=False)]

,ACCOUNTNO,PARCELNO,ACCTTYPE,TAXAREA,IMPNO,TOTALUNITCOUNT,IMPSF,PROPERTYTYPE,TOTALVALUE,ACRES,LANDVALUE,IMPEXTERIOR,BLTASSTORIES,BLTASYEARBUILT,BLTASDESCRIPTION,PRIMARY_NONPRIMARY,STREETNO,PREDIRECTION,STREETNAME,PROPERTYCITY,STREETTYPE,PROPERTYZIPCODE,SITUS,SUBDIVISIONNAME
18,250,SG-17-B,Commercial,8,1.0,3.0,3643.0,Triplex,831600,0.23,149500,Frame Stucco,1.5,2003.0,Triplex 1 1/2 Story,OTHER RES-INC MULTI FAMILY-PRIM,260,S,200 E,ST GEORGE,ST,847700000.0,260 S 200 E ST ST GEORGE 847700000,ST GEORGE CITY SURVEY
19,250,SG-17-B,Commercial,8,1.0,3.0,3643.0,Triplex,831600,0.23,149500,Frame Stucco,1.5,2003.0,Triplex 1 1/2 Story,OTHER RES-INC MULTI FAMILY-PRIM,252,S,200 E,ST GEORGE,ST,847700000.0,252 S 200 E ST ST GEORGE 847700000,ST GEORGE CITY SURVEY
20,250,SG-17-B,Commercial,8,1.0,3.0,3643.0,Triplex,831600,0.23,149500,Frame Stucco,1.5,2003.0,Triplex 1 1/2 Story,OTHER RES-INC MULTI FAMILY-PRIM,256,S,200 E,ST GEORGE,ST,847700000.0,256 S 200 E ST ST GEORGE 847700000,ST GEORGE CITY SURVEY
42,623,SG-43,Residential,8,1.0,1.0,688.0,Residential,254500,0.08,80800,Frame Stucco,1.0,1943.0,Ranch 1 Story,RES IMPROVEMENT-PRIMARY,26,W,300 S,ST GEORGE,ST,847700000.0,26 W 300 S ST ST GEORGE 847700000,ST GEORGE CITY SURVEY
43,623,SG-43,Residential,8,1.0,1.0,688.0,Residential,254500,0.08,80800,Frame Stucco,1.0,1943.0,Ranch 1 Story,RES IMPROVEMENT-PRIMARY,28,W,300 S,ST GEORGE,ST,84770.0,28 W 300 S ST ST GEORGE 84770,ST GEORGE CITY SURVEY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102460,1997678,SG-1267,Commercial,8,1.0,1.0,1065.0,Commercial,340600,0.20,127200,NaN,1.0,1946.0,Office Building,SERVICE,47.0,N,600 E,ST GEORGE,ST,847700000.0,47 N 600 E ST ST GEORGE 847700000,ST GEORGE CITY SURVEY
102461,1997678,SG-1267,Commercial,8,2.0,1.0,3193.0,Commercial,340600,0.20,127200,NaN,1.0,1984.0,Equipment Storage,SERVICE,47.0,N,600 E,ST GEORGE,ST,847700000.0,47 N 600 E ST ST GEORGE 847700000,ST GEORGE CITY SURVEY
102462,1997678,SG-1267,Commercial,8,2.0,0.0,3193.0,Commercial,340600,0.20,127200,NaN,1.0,1984.0,Material Storage Sheds,SERVICE,47.0,N,600 E,ST GEORGE,ST,847700000.0,47 N 600 E ST ST GEORGE 847700000,ST GEORGE CITY SURVEY
102480,1997900,SG-711-C-4,Commercial,8,1.0,0.0,400.0,Commercial,784000,14.67,624600,NaN,1.0,2020.0,Pavilions,EXEMPT IMPROVEMENT,265.0,NaN,TECH RIDGE,ST GEORGE,DR,74770.0,NaN,NaN
102481,1997900,SG-711-C-4,Commercial,8,2.0,0.0,400.0,Commercial,784000,14.67,624600,NaN,1.0,2020.0,Pavilions,EXEMPT IMPROVEMENT,265.0,NaN,TECH RIDGE,ST GEORGE,DR,74770.0,NaN,NaN

In [7]:
wascho_cama_df["PROPERTYTYPE"].value_counts()

PROPERTYTYPE
Residential      60250
Townhouse         8920
Commercial        6551
Mobile Home       3366
Condo             2034
Out Building      1162
Duplex             614
Multiple Unit      603
Triplex            121
Name: count, dtype: int64

In [8]:
#: Duplicates in the cama data may occur where parcelno and impno are the same
cama_dups = wascho_cama_df.duplicated(subset=["PARCELNO", "IMPNO"], keep="first")
wascho_cama_df.drop_duplicates(subset=["PARCELNO", "IMPNO"], keep="first", inplace=True)

In [9]:
#: dissolving parcels on ID (small slivers, etc)
dissolved_parcels_df = pd.DataFrame.spatial.from_featureclass(r"C:\gis\Projects\HousingInventory\WashingtonCo.gdb\washco_20231214_dissolved")
dissolved_parcels_df.head()

   OBJECTID PARCEL_ID                                              SHAPE
0         1    1-A-HV  {"rings": [[[322726.22190000024, 4151003.9616]...
1         2    1-B-HV  {"rings": [[[323527.62260000035, 4150984.54990...
2         3      1-TR  {"rings": [[[331012.1464999998, 4096955.335699...
3         4     10-HV  {"rings": [[[324336.6283, 4151763.2798999995],...
4         5  100-A-HV  {"rings": [[[323377.4182000002, 4142621.0308],...

In [10]:
#: Get null parcels that won't join to a cama record
washco_parcels_df = pd.DataFrame.spatial.from_featureclass(r"C:\gis\Projects\HousingInventory\WashingtonCo.gdb\washco_20231214")
null_ids = washco_parcels_df[washco_parcels_df["PARCEL_ID"].isnull()].reindex(columns=["OBJECTID", "SHAPE", "PARCEL_ID"])

In [11]:
all_parcels = pd.concat([null_ids, dissolved_parcels_df])
len(all_parcels)

108708

In [32]:
# merged = dissolved_parcels_df.merge(wascho_cama_df, left_on="PARCEL_ID", right_on="PARCELNO", how="left")
basic_cama_merged = all_parcels.merge(wascho_cama_df, left_on="PARCEL_ID", right_on="PARCELNO", how="left")
# merged[merged["PARCELNO"].isnull()]
# merged.head()
basic_cama_merged = basic_cama_merged.convert_dtypes()
# merged["PROPERTYZIPCODE"] = merged["PROPERTYZIPCODE"].astype("string")
# merged["STREETNO"] = merged["STREETNO"].astype("string")
basic_cama_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112801 entries, 0 to 112800
Data columns (total 27 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   OBJECTID            112801 non-null  Int64
 1   SHAPE               112801 non-null  geometry
 2   PARCEL_ID           103024 non-null  string
 3   ACCOUNTNO           102781 non-null  Int64
 4   PARCELNO            102781 non-null  string
 5   ACCTTYPE            102781 non-null  string
 6   TAXAREA             102781 non-null  Int64
 7   IMPNO               82929 non-null   Int64
 8   TOTALUNITCOUNT      82913 non-null   Int64
 9   IMPSF               82929 non-null   Int64
 10  PROPERTYTYPE        82929 non-null   string
 11  TOTALVALUE          102781 non-null  Int64
 12  ACRES               102781 non-null  Float64
 13  LANDVALUE           102781 non-null  Int64
 14  IMPEXTERIOR         76147 non-null   string
 15  BLTASSTORIES        82925 non-null   Float64
 16  BLTASYEARBUILT      82929 non-null   Int64
 17  BLTASDESCRIPTION    82929 non-null   string
 18  PRIMARY_NONPRIMARY  82929 non-null   string
 19  STREETNO            81825 non-null   object
 20  PREDIRECTION        77039 non-null   string
 21  STREETNAME          81943 non-null   string
 22  PROPERTYCITY        82294 non-null   string
 23  STREETTYPE          61320 non-null   string
 24  PROPERTYZIPCODE     78852 non-null   object
 25  SITUS               54028 non-null   string
 26  SUBDIVISIONNAME     86927 non-null   string
dtypes: Float64(2), Int64(9), geometry(1), object(2), string(13)
memory usage: 24.4+ MB

In [13]:
# merged = merged.reindex(columns=["PARCEL_ID", "SHAPE", "ACCOUNTNO", "PARCELNO", "ACCTTYPE", "TAXAREA", "IMPNO", "TOTALUNITCOUNT", "IMPSF", "PROPERTYTYPE", "TOTALVALUE", "LANDVALUE", "IMPEXTERIOR", "BLTASSTORIES", "BLTASYEARBUILT", "BLTASDESCRIPTION", "PRIMARY_NONPRIMARY", "SUBDIVISIONNAME"])
basic_cama_merged.drop(columns="PROPERTYZIPCODE").spatial.to_featureclass(location=r"C:\gis\Projects\HousingInventory\WashingtonCo.gdb\washco_20231214_cama")

ExecuteError: ERROR 000464: Cannot get exclusive schema lock.  Either being edited or in use by another application or service.
Failed to execute (Delete).

In [13]:
wascho_cama_df[wascho_cama_df["PARCELNO"]=="SG-BG-2-22-A-1"]

,ACCOUNTNO,PARCELNO,ACCTTYPE,TAXAREA,IMPNO,TOTALUNITCOUNT,IMPSF,PROPERTYTYPE,TOTALVALUE,ACRES,LANDVALUE,IMPEXTERIOR,BLTASSTORIES,BLTASYEARBUILT,BLTASDESCRIPTION,PRIMARY_NONPRIMARY,STREETNO,PREDIRECTION,STREETNAME,PROPERTYCITY,STREETTYPE,PROPERTYZIPCODE,SITUS,SUBDIVISIONNAME
11944,139330,SG-BG-2-22-A-1,Residential,8,3.0,1.0,1230.0,Out Building,820200,2.48,157200,NaN,1.0,2018.0,Farm Utility Building,RES IMPROVEMENT-PRIMARY,1267,W,MARIGOLD,ST GEORGE,WAY,847900000.0,1267 W MARIGOLD WAY ST GEORGE 847900000,BLOOMINGTON GARDENS 2
11945,139330,SG-BG-2-22-A-1,Residential,8,1.0,1.0,2637.0,Residential,820200,2.48,157200,Frame Stucco,1.0,1979.0,Ranch 1 Story,RES IMPROVEMENT-PRIMARY,1267,W,MARIGOLD,ST GEORGE,WAY,847900000.0,1267 W MARIGOLD WAY ST GEORGE 847900000,BLOOMINGTON GARDENS 2
11946,139330,SG-BG-2-22-A-1,Residential,8,2.0,1.0,2351.0,Residential,820200,2.48,157200,Frame Stucco,1.0,2004.0,Ranch 1 Story,RES IMPROVEMENT-PRIMARY,1267,W,MARIGOLD,ST GEORGE,WAY,847900000.0,1267 W MARIGOLD WAY ST GEORGE 847900000,BLOOMINGTON GARDENS 2

In [14]:
wascho_cama_df[(wascho_cama_df.duplicated(subset=["PARCELNO"], keep=False)) & (wascho_cama_df["PROPERTYTYPE"] != "Commercial")]["PROPERTYTYPE"].value_counts()

PROPERTYTYPE
Residential      2235
Out Building      734
Multiple Unit     386
Mobile Home       191
Duplex            119
Triplex            39
Townhouse          22
Name: count, dtype: int64

In [15]:
wascho_cama_df[wascho_cama_df["PROPERTYTYPE"] != "Commercial"]["PROPERTYTYPE"].value_counts()

PROPERTYTYPE
Residential      60103
Townhouse         8918
Mobile Home       3362
Condo             2034
Out Building      1142
Multiple Unit      574
Duplex             466
Triplex             73
Name: count, dtype: int64

In [23]:
def combine_cama_parcels(df):
    df = df[df["PROPERTYTYPE"] != "Out Building"]  #: Filter out records that are outbuildings
    
    attrs_dict = {}
    attrs_dict["PARCELNO"] = df["PARCELNO"].iloc[0]

    #: These should take the most common value
    for mode_column in ["PROPERTYTYPE", "PRIMARY_NONPRIMARY", "SUBDIVISIONNAME"]:
        try:
            attrs_dict[mode_column] = df[mode_column].mode()[0]
        except Exception:
            attrs_dict[mode_column] = pd.NA

    #: These should get the sum
    for sum_column in ["TOTALUNITCOUNT", "IMPSF"]:
        try:
            attrs_dict[sum_column] = df[sum_column].sum()
        except Exception:  
            attrs_dict[sum_column] = 0

    #: Year built should be the most common year, but if that's 0, it should be the max
    try:
        year_built = df["BLTASYEARBUILT"].mode()[0]
        attrs_dict["BLTASYEARBUILT"] = year_built if year_built != 0 else df["BLTASYEARBUILT"].max()
    except Exception:
        attrs_dict["BLTASYEARBUILT"] = 0

    for max_column in ["TOTALVALUE"]:
        try:
            attrs_dict[max_column] = df[max_column].max()
        except Exception:
            attrs_dict[max_column] = 0

    # if df['PROPERTYTYPE'].str.contains('Multiple Unit').any():
    #     attrs_dict['TOTALVALUE'] = df['TOTALVALUE'].max()
    # else:
    #     attrs_dict['TOTALVALUE'] = df['TOTALVALUE'].sum()

    return pd.Series(attrs_dict)

In [24]:
wascho_cama_df[wascho_cama_df["PROPERTYTYPE"] != "Out Building"].groupby("PARCELNO").get_group("SG-BG-2-22-A-1")["BLTASYEARBUILT"].mode().max()

2004.0

In [25]:
combine_cama_parcels(wascho_cama_df.groupby("PARCELNO").get_group("SG-BG-2-22-A-1"))

PARCELNO                       SG-BG-2-22-A-1
PROPERTYTYPE                      Residential
PRIMARY_NONPRIMARY    RES IMPROVEMENT-PRIMARY
SUBDIVISIONNAME         BLOOMINGTON GARDENS 2
TOTALUNITCOUNT                            2.0
IMPSF                                  4988.0
BLTASYEARBUILT                         1979.0
TOTALVALUE                             820200
dtype: object

In [26]:
grouped = wascho_cama_df[wascho_cama_df["PROPERTYTYPE"].isin(["Residential", "Townhouse", "Mobile Home", "Condo", "Duplex", "Triplex", "Multiple Unit"])].groupby("PARCELNO")
group_iter = iter(grouped)

group[1]

In [27]:
combined_cama_df = grouped.apply(combine_cama_parcels)

In [28]:
wascho_cama_df[wascho_cama_df["PROPERTYTYPE"].isin(["Residential", "Townhouse", "Mobile Home", "Condo", "Duplex", "Triplex", "Multiple Unit"])].sort_values(by="PARCELNO")

,ACCOUNTNO,PARCELNO,ACCTTYPE,TAXAREA,IMPNO,TOTALUNITCOUNT,IMPSF,PROPERTYTYPE,TOTALVALUE,ACRES,LANDVALUE,IMPEXTERIOR,BLTASSTORIES,BLTASYEARBUILT,BLTASDESCRIPTION,PRIMARY_NONPRIMARY,STREETNO,PREDIRECTION,STREETNAME,PROPERTYCITY,STREETTYPE,PROPERTYZIPCODE,SITUS,SUBDIVISIONNAME
36737,442890,1000-D-HV,Residential,47,1.0,1.0,742.0,Residential,89360,93.07,10660,Pine Finished Cabin,1.5,2000.0,Cabin,RESIDENTIAL - NON-PRIMARY,NaN,NaN,NaN,KOLOB,NaN,0.0,NaN,NaN
37878,454655,1000-E-HV,Residential,47,1.0,1.0,686.0,Residential,172990,166.04,18690,Frame Plywood,1.0,1980.0,Ranch 1 Story,RESIDENTIAL - NON-PRIMARY,NaN,NaN,NaN,KOLOB,NaN,0.0,NaN,NaN
37879,454655,1000-E-HV,Residential,47,2.0,1.0,672.0,Residential,172990,166.04,18690,Cedar Finished Cabin,1.0,2012.0,Cabin,RESIDENTIAL - NON-PRIMARY,NaN,NaN,NaN,KOLOB,NaN,0.0,NaN,NaN
16674,204464,10001,Residential,15,2.0,1.0,812.0,Residential,268546,17.26,10446,Frame Siding,1.0,2000.0,Ranch 1 Story,RESIDENTIAL - NON-PRIMARY,4823,N,BEAVER DAM WASH,MOTOQUA,RD,NaN,NaN,NaN
16676,204464,10001,Residential,15,3.0,1.0,1221.0,Residential,268546,17.26,10446,Masonry Poured Concrete,1.0,2018.0,Ranch 1 Story,RESIDENTIAL - NON-PRIMARY,4823,N,BEAVER DAM WASH,MOTOQUA,RD,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20367,246309,ZP-42-HV,Residential,47,1.0,1.0,560.0,Residential,97100,1.75,23400,Frame Siding,1.0,1986.0,Ranch 1 Story,RESIDENTIAL - NON-PRIMARY,53,N,BOX CANYON,KOLOB,RD,84767.0,53 N BOX CANYON RD KOLOB 84767,ZION PANORAMA
20368,246317,ZP-43-HV,Residential,47,1.0,1.0,144.0,Residential,48800,1.65,22900,Frame Siding,1.0,1986.0,Ranch 1 Story,RESIDENTIAL - NON-PRIMARY,45,N,BOX CANYON,KOLOB,RD,84767.0,45 N BOX CANYON RD KOLOB 84767,ZION PANORAMA
12657,146855,ZP-5-1-HV,Residential,47,1.0,1.0,2380.0,Residential,445200,20.83,73500,Frame Siding,1.5,2021.0,1 1/2 Story Fin,RESIDENTIAL - NON-PRIMARY,351,N,BOX CANYON,KOLOB,RD,84767.0,351 N BOX CANYON RD KOLOB 84767,ZION PANORAMA 5
20332,245954,ZP-7-HV,Residential,47,1.0,1.0,864.0,Residential,149700,1.79,23600,Frame Siding,1.5,1984.0,Ranch 1 Story,RESIDENTIAL - NON-PRIMARY,32,N,BOX CANYON,KOLOB,RD,84767.0,32 N BOX CANYON RD KOLOB 84767,ZION PANORAMA
20333,245962,ZP-8-HV,Residential,47,1.0,1.0,768.0,Residential,159500,1.44,22000,Frame Hardboard,1.5,1999.0,Ranch 1 Story,RESIDENTIAL - NON-PRIMARY,38,N,BOX CANYON,KOLOB,RD,84767.0,38 N BOX CANYON RD KOLOB 84767,ZION PANORAMA

In [29]:
merged = all_parcels.merge(combined_cama_df.reset_index(drop=True), left_on="PARCEL_ID", right_on="PARCELNO", how="left").convert_dtypes()
merged.spatial.to_featureclass(location=r"C:\gis\Projects\HousingInventory\WashingtonCo.gdb\washco_20231214_cama_groupedres")

'C:\\gis\\Projects\\HousingInventory\\WashingtonCo.gdb\\washco_20231214_cama_groupedres'

# Script Testing

In [1]:
import pandas as pd
import arcgis
from housing_unit_inventory import dissolve
from pathlib import Path

In [2]:
#: Load cama data, remove dupes (parcel no and imp no are the same)
wascho_cama_df = pd.read_csv("C:\gis\Projects\HousingInventory\Data\Washington\WashCo_cama.csv", thousands=",")
wascho_cama_df.drop_duplicates(subset=["PARCELNO", "IMPNO"], keep="first", inplace=True)

C:\Users\jdadams\AppData\Local\Temp\1\ipykernel_7600\3639455697.py:2: DtypeWarning: Columns (16,21) have mixed types. Specify dtype option on import or set low_memory=False.
  wascho_cama_df = pd.read_csv("C:\gis\Projects\HousingInventory\Data\Washington\WashCo_cama.csv", thousands=",")

In [7]:
#: Load parcel geometries, separate null parcel ids, dissolve non-null parcel ids, recombine
washco_parcels_df = pd.DataFrame.spatial.from_featureclass(r"C:\gis\Projects\HousingInventory\WashingtonCo.gdb\washco_20231214")
null_ids = washco_parcels_df[washco_parcels_df["PARCEL_ID"].isnull()].reindex(columns=["OBJECTID", "SHAPE", "PARCEL_ID"]).copy()
non_null_ids = washco_parcels_df[~washco_parcels_df["PARCEL_ID"].isnull()].reindex(columns=["OBJECTID", "SHAPE", "PARCEL_ID"]).copy()

In [13]:
dupes, non_dupes = dissolve._extract_duplicates_and_uniques(non_null_ids, "PARCEL_ID")
dissolved = dissolve._dissolve_geometries(dupes, "PARCEL_ID")
combined = pd.concat([dissolved, non_dupes, null_ids])

In [23]:
input_gdb = Path(r"C:\gis\Projects\HousingInventory\WashingtonCo.gdb")
input_gdb.parent / "foo/bar"

WindowsPath('C:/gis/Projects/HousingInventory/foo/bar')

In [8]:
try:
    raise ValueError("borked")
except ValueError as error:
    print(error.args)

('borked',)

In [12]:
wascho_cama_df[wascho_cama_df["PROPERTYTYPE"] == "Commercial"]["BLTASDESCRIPTION"].value_counts().sort_index()

BLTASDESCRIPTION
Apartments (Hi-Rise)                    4
Arcade                                  1
Auditorium                              1
Automotive Center                      70
Bank                                   42
Banquet Halls                           3
Bar/Tavern                              3
Bath Houses                             1
Bed And Breakfast Inns                 29
Bowling Alley                           3
Car Wash - Automatic                   12
Car Wash - Drive thru                   2
Car Wash - Self Service                13
Central Bank                            8
Church                                107
Church w/Sunday School                  1
Clubhouse                              48
Cold Storage Warehouse                  2
College - Classrooms                    4
Community Recreation Center             5
Community Shopping Center              10
Commuter Terminal, Airline, Bus         2
Complete Auto Dealership               27
Computer Centers                        1
Convenience Store                       1
Convention Center                       2
Convlsnt Hosp Nursing Home              8
Country Club                            4
Day Care Center                        10
Dental Office/ Clinic                  32
Department Store                        1
Discount Store                         10
Distribution Warehouse                  7
Drive-up Mini Banks                     5
Drug Store                              3
Equipment Storage                     158
Fast Food Restaurant                   81
Fire Station - Volunteer                7
Fire Station Staffed                    6
Firing Range Buildings                  9
Fitness Center                         16
Fraternity                              1
Golf Cart Storage Bldgs                 3
Group Care Homes                       60
Health Club                             2
Hospital                                3
Hotel - Full Service                    1
Hotels - Limited Service               49
Indust Lght Manufacturing             458
Industrial Flex Mall Building         375
Jail - Correctional Facility            2
Laundromat                             13
Laundry/Dry Cleaning                    1
Library - Public                        8
Light Industrial Shell Buildings      151
Lodges                                  2
Maintenance (Storage) Buildings        12
Market                                  6
Material Shelters                      57
Material Storage Sheds                 57
Medical Offices                        46
Mega Warehouse                          3
Mega Warehouse Stores                   3
Middle (Junior High) Schools            1
Mini Lube Garage                       10
Mini Warehouse                        409
Mini Warehouse Hi-rise                  1
Mini-Mart Convenience Stores           54
Mixed Retail w/ Office Units            1
Mixed Retail w/ Res Units               1
Mobile Home/RV Parks  *CODE            52
Modular Office                         35
Mortuary                                7
Motel                                 275
Multiple - Elderly Assisted Living     39
Museum                                  6
Neighborhood Shopping Center          345
Neighborhood Shopping Center Shell      5
Nursery/Greenhouse                     13
Office Building                       885
Office-Apartment                        6
Parking Structure                       5
Pavilions                              72
Permit Value *COM                     369
Permit Value *RES                       1
Post Office                             7
Quonset                                12
Recreational Pool Enclosure             6
Regional Shopping Center                2
Relocatable Classroom                   6
Restaurant                            104
Restroom Building/Concessions          89
Retail Store                          251
Roadside Markets                        1
School - Classroom                      1
School - Elementary/Secondary          16
School - Gymnasium                      8
School - Manual Arts                    1
Self Service Booth                      5
Senior (Clubhouse) Centers              3
Service Garage                         35
Service Station                         2
Shed Office Structure                  20
Shower Building                         4
Showroom                                1
Stadiums  *CODE                         1
Storage - Utility Grain                 1
Storage Hangar                        155
Storage Warehouse                       2
SuperMarket                            11
Surgical Center - Out patient           3
T-Hangar                               21
Tanks  *CODE                            1
Theatre - Motion                        6
Theatre - Stage                         6
Transit Warehouse                       4
Urgent Care Clinics                     3
Veterinary Hospital                    11
Visitor Center                          1
Warehouse Discount Store               15
Warehouse Food Store                    1
Warehouse Showroom Store               18
Winery (Tasting-Display) Shops          2
Name: count, dtype: int64

In [9]:
#: show all dataframe columns in jupyter notebook
pd.set_option("display.max_rows", None)

In [3]:
wascho_cama_df.head()

,ACCOUNTNO,PARCELNO,ACCTTYPE,TAXAREA,IMPNO,TOTALUNITCOUNT,IMPSF,PROPERTYTYPE,TOTALVALUE,ACRES,LANDVALUE,IMPEXTERIOR,BLTASSTORIES,BLTASYEARBUILT,BLTASDESCRIPTION,PRIMARY_NONPRIMARY,STREETNO,PREDIRECTION,STREETNAME,PROPERTYCITY,STREETTYPE,PROPERTYZIPCODE,SITUS,SUBDIVISIONNAME
0,11,SG-1-A,Residential,8,1.0,1.0,2268.0,Residential,482400,0.21,97800,Frame Stucco,1.0,1940.0,1 1/2 Story Fin,RES IMPROVEMENT-PRIMARY,175,E,300 S,ST GEORGE,ST,84770.0,175 E 300 S ST ST GEORGE 84770,ST GEORGE CITY SUR PLAT A BLK 1
1,37,SG-1-C,Residential,8,1.0,1.0,1496.0,Residential,385200,0.23,97800,Frame Masonry Veneer,1.0,1975.0,Ranch 1 Story,RES IMPROVEMENT-PRIMARY,185,E,300 S,ST GEORGE,ST,847700000.0,185 E 300 S ST ST GEORGE 847700000,ST GEORGE CITY SURVEY
2,45,SG-2,Residential,8,1.0,1.0,1363.0,Residential,294600,0.09,72300,Frame Stucco,1.0,1924.0,Ranch 1 Story,RES IMPROVEMENT-PRIMARY,286,S,200 E,ST GEORGE,ST,847700000.0,286 S 200 E ST ST GEORGE 847700000,ST GEORGE CITY SURVEY
3,52,SG-3-A,Residential,8,1.0,1.0,2489.0,Residential,679500,0.27,97800,Frame Stucco,1.0,2006.0,Ranch 1 Story,RES IMPROVEMENT-PRIMARY,167,E,300 S,ST GEORGE,ST,847700000.0,167 E 300 S ST ST GEORGE 847700000,ST GEORGE CITY SURVEY
4,60,SG-4,Residential,8,1.0,1.0,832.0,Residential,266200,0.10,76500,Frame Stucco,1.0,1910.0,Ranch 1 Story,RESIDENTIAL - NON-PRIMARY,105,E,300 S,ST GEORGE,ST,847700000.0,105 E 300 S ST ST GEORGE 847700000,ST GEORGE CITY SURVEY

In [11]:
mean_series = wascho_cama_df.groupby("PROPERTYCITY")["IMPSF"].mean()
mean_series.name = "mean"
sum_series = wascho_cama_df.groupby("PROPERTYCITY")["IMPSF"].sum()
sum_series.name = "sum"

In [12]:
pd.concat([mean_series, sum_series], axis=1)

                         mean          sum
PROPERTYCITY
APPLE VALLEY      1970.948661     882985.0
BROOKSIDE         1875.211111     337538.0
CENTRAL           1624.111872     711361.0
DAMMERON VALLEY   2346.711066    1145195.0
DIAMOND VALLEY    2238.720588     761165.0
ENTERPRISE        2138.338852    1937335.0
GUNLOCK           2074.129870     159708.0
HILDALE           4207.240209    1611373.0
HURRICANE         2547.433583   24182787.0
IVINS             2259.007535   10192642.0
KOLOB             1020.539267     389846.0
LA VERKIN         1877.777509    3105844.0
LEEDS             2230.949324    1320722.0
MOTOQUA           2081.888889      56211.0
NEW HARMONY       2303.986436    1868533.0
PINE VALLEY       1825.809963     989589.0
PINTO             1429.277778      51454.0
PINTURA           2024.210526      38460.0
ROCKVILLE         1698.920213     319397.0
SANTA CLARA       2432.991453    7116500.0
SMITH MESA        1078.533333      16178.0
SPRINGDALE        2723.487302    1715797.0
ST GEORGE         2613.177923  108023549.0
TOQUERVILLE       2121.915254    1627509.0
VEYO              2056.771429     575896.0
VIRGIN            1954.113580     791416.0
WASHINGTON        2331.635477   31073706.0
WINCHESTER HILLS  2219.172316     785587.0